#!/bin/bash
#
# Download and install cross-compile tools if necessary.  If there is
# a cross-compiler already in the path, assume all is ready and there
# is nothing to do.
#
# In some cases, it may be necessary to download & install the latest
# EPEL7 repo information to get to the right packages.
#
# Argument(s) to this script is a list of rpm names to install.

# if everything is installed then exit successfully
if rpm -q "$@"; then
	echo "All cross-tools installed and ready."
	exit 0
else
	echo "Attempting to install cross-tools..."
fi

# install epel-release if necessary

rpm -q epel-release >& /dev/null || \
	dnf install -y \
	https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# install list of rpms for cross compile
sudo dnf -y install "$@"

exit 0
